spring:
  datasource:
    url: jdbc:mysql://localhost:3306/root?serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com: debug

